export const DIALOGS = [
  {
    count: 0,
    width: 220,
    height: 120,
    text: "The latest news! The zombie has been found in a small town - SmallTown! If you'l see anyone, please, be careful! Better stay at home!",
    coordinates: [5380, 5580],
    delay: 7000,
  },
  {
    count: 1,
    width: 120,
    height: 120,
    text: 'What?.... It cannot be true! But I heard something...',
    delay: 1500,
  },
  {
    count: 2,
    width: 120,
    height: 120,
    text: 'Who are you? What are you doing here?... Omg!!! Die!!!',
    delay: 1500,
  },
  {
    count: 3,
    width: 120,
    height: 120,
    text: 'I need a better weapon and get out of here!',
    delay: 2000,
  },
  {
    count: 4,
    width: 120,
    height: 60,
    text: 'Zombie! Again! Die!!!!',
    delay: 1500,
  },
  {
    count: 5,
    width: 120,
    height: 120,
    text: 'This zombie was big! I think our police was destroyed, but I have to find survivals...',
    delay: 3000,
  },
  {
    count: 6,
    width: 120,
    height: 120,
    text: 'It is like in a horror movie!',
    delay: 1500,
  },
  {
    count: 7,
    width: 120,
    height: 60,
    text: 'It was nice shot!',
    delay: 1500,
  },
  {
    count: 8,
    width: 100,
    height: 50,
    text: 'I am the Flash!!!',
    delay: 2000,
  },
  {
    count: 9,
    width: 100,
    height: 50,
    text: 'MedKit!...Nice!',
    delay: 2000,
  },
  {
    count: 10,
    width: 100,
    height: 50,
    text: 'Slow down, buddy!',
    delay: 2000,
  },
  {
    count: 11,
    width: 100,
    height: 50,
    text: 'RAGE!!!!',
    delay: 2000,
  },
  {
    count: 12,
    width: 100,
    height: 50,
    text: 'RAGE!!!!',
    delay: 2000,
  },
  {
    count: 13,
    width: 120,
    height: 50,
    text: '21 killed zombie! Bingo!',
    delay: 2000,
  },
  {
    count: 14,
    width: 120,
    height: 50,
    text: '50...100... Who cares?',
    delay: 2000,
  },
  {
    count: 15,
    width: 220,
    height: 120,
    text: "I've tried to leave this town in South... But it isn't possible. But some citizen said - there is an exit on the other side our river...",
    coordinates: [535, 737],
    delay: 7000,
  },
];
