export const DIALOGS = [
  {
    count: 1,
    width: 220,
    height: 120,
    text: "The latest news! The zombie has been found in a small town - SmallTown! If you'l see anyone, please, be careful! Better stay at home!",
    coordinates: [5380, 5580],
    delay: 7000,
  },
  {
    count: 2,
    width: 120,
    height: 120,
    text: 'What?.... It cannot be true! But I heard something...',
    delay: 3000,
  },
  {
    count: 3,
    width: 120,
    height: 120,
    text: 'Who are you? What are you doing here?... Omg!!! Die!!!',
    delay: 3000,
  },
  {
    count: 4,
    width: 120,
    height: 120,
    text: 'I need a better weapon and get out of here!',
    delay: 2500,
  },
  {
    count: 5,
    width: 120,
    height: 60,
    text: 'Zombie! Again! Die!!!!',
    delay: 2000,
  },
  {
    count: 6,
    width: 120,
    height: 120,
    text: 'This zombie was big! I think our police was destroyed, but I have to find survivals...',
    delay: 4000,
  },
  {
    count: 7,
    width: 120,
    height: 120,
    text: 'It is like in a horror movie!',
    delay: 2000,
  },
  {
    count: 7,
    width: 120,
    height: 120,
    text: 'It was nice shot!',
    delay: 2000,
  },
];
