export const IMAGES = [
  { name: 'secondIcon', url: './assets/game/ui/element_0074_Layer-76.png' },
  { name: 'health', url: './assets/game/items/items_0005_health.png' },
  { name: 'speed', url: './assets/game/items/items_0006_speed.png' },
  { name: 'slow', url: './assets/game/items/items_0007_slow_enemies.png' },
  { name: 'damage', url: './assets/game/items/items_0008_superpower.png' },
  { name: 'floor', url: './assets/game/tiles/floor.png' },
  { name: 'iconMan', url: './assets/game/icons/manicon.png' },
  { name: 'walls', url: './assets/game/tiles/walls.png' },
  { name: 'roof2', url: './assets/game/tiles/roof2.png' },
  { name: 'other', url: './assets/game/tiles/other.png' },
  { name: 'gun', url: './assets/game/items/gun.png' },
  { name: 'rifle', url: './assets/game/items/rifle.png' },
  { name: 'bat', url: './assets/game/items/bat.png' },
  { name: 'firethrower', url: './assets/game/items/firethrower.png' },
  { name: 'knife', url: './assets/game/items/knife.png' },
  { name: 'furniture', url: './assets/game/tiles/furniture.png' },
  { name: 'other2', url: './assets/game/tiles/other2.png' },
  { name: 'btn-settings', url: './assets/game/ui/btn-settings.png' },
  { name: 'settings-menu', url: './assets/game/ui/settings-menu.png' },
  { name: 'bullet', url: './assets/game/bullet1.png' },
  { name: 'empty-item', url: './assets/game/ui/element_0018_Layer-20.png' },
  { name: 'active-item', url: './assets/game/ui/element_0017_Layer-19.png' },
];
