export const IMAGES = [
  { name: 'uiPanel', url: './assets/game/ui/element_0074_Layer-76.png' },
  { name: 'uiPanel-light', url: './assets/game/ui/uiPanel-light.png' },
  { name: 'health', url: './assets/game/items/items_0005_health.png' },
  { name: 'speed', url: './assets/game/items/items_0006_speed.png' },
  { name: 'slow', url: './assets/game/items/items_0007_slow_enemies.png' },
  { name: 'floor', url: './assets/game/tiles/floor.png' },
  { name: 'tech', url: './assets/game/tiles/tech.png' },
  { name: 'walls', url: './assets/game/tiles/walls.png' },
  { name: 'roof2', url: './assets/game/tiles/roof2.png' },
  { name: 'other', url: './assets/game/tiles/other.png' },
  { name: 'fire', url: './assets/game/items/fire.png' },
  { name: 'pistol', url: './assets/game/items/pistol.png' },
  { name: 'rifle', url: './assets/game/items/rifle.png' },
  { name: 'shotgun', url: './assets/game/items/shotgun.png' },
  { name: 'sniper', url: './assets/game/items/sniper.png' },
  { name: 'flamethrower', url: './assets/game/items/flamethrower.png' },
  { name: 'knife', url: './assets/game/items/knife.png' },
  { name: 'furniture', url: './assets/game/tiles/furniture.png' },
  { name: 'other2', url: './assets/game/tiles/other2.png' },
  { name: 'btn-settings', url: './assets/game/ui/btn-settings.png' },
  { name: 'settings-menu', url: './assets/game/ui/settings-menu.png' },
  { name: 'bullet', url: './assets/game/ui/bullet.png' },
  { name: 'bullet-shotgun', url: './assets/game/ui/bullet-shotgun.png' },
  { name: 'empty-item', url: './assets/game/ui/element_0018_Layer-20.png' },
  { name: 'active-item', url: './assets/game/ui/element_0017_Layer-19.png' },
  { name: 'settings-menu', url: './assets/game/ui/settings-menu.png' },
];
